micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:mysql://localhost/micronaut-ksa-do-kodigo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    schema-generate: CREATE_DROP
    dialect: MySQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      show_sql: true